name: "Docs: Check and Deploy"

on:
  push:
    branches: [main, github-actions-test]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.11]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Packages
        run: uv sync --group docs

      - name: Install Pandoc [apt-get]
        run: |
          sudo apt-get -y install pandoc

      - name: Document Validation
        run: uv run numpydoc lint test/**/*.py topoembedx/**/*.py

      - name: Generate Docs [Sphinx]
        run: uv run sphinx-build  -b html -D version=latest -D release=latest docs docs/_build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pyt-team/TopoEmbedX' }}
        with:
          branch: main
          folder: docs/_build
          token: ${{ secrets.DOCUMENTATION_KEY }}
          repository-name: pyt-team/pyt-team.github.io
          target-folder: topoembedx
          clean: true
